[package]
name = "monagement"
version = "0.0.3"
edition = "2024"
description = "TLSF Memory Management"
keywords = ["memory", "allocator", "tlsf", "memory-management", "management"]
license = "Apache-2.0"

[lib]
name = "monagement"
path = "src/lib.rs"


[dependencies]
rand = "0.9.2"
